version: '3.7'
services:
  app:
    image: localrepo/app
    build:
      context: app/
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: flask_app_db
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql


  liquibase:
    image: liquibase/liquibase:${liquibase_tag_version:-4.9.1}
    profiles: ["no-autostart"]
    env_file:
      - .env
    volumes:
      - ./ddl/mysql:/liquibase/ddl/mysql
      - ./conf/liquibase.properties:/liquibase/liquibase.properties
      - ./conf/liquibase.changelog.xml:/liquibase/changelog.xml
      - ./lib/drivers/mysql-connector-java-5.1.46.jar:/liquibase/mysql-connector-java.jar
    depends_on:
      - db
    command: update --defaults-file=liquibase.properties --changelog-file=changelog.xml
